### ISSUE TITLE
PyPI

### ISSUE THREAD

**Issue by jayvdb** [stricaud/gvgen#11]
Any chance you could release this on PyPI?

The problem of https://github.com/EFForg/https-everywhere/issues/6466 still exists in https://github.com/hiviah/https-everywhere-checker/blob/master/src/https_everywhere_checker/gvgen.py , and can be solved by de-vendoring it from that repository so it can be a dep of https://pypi.org/project/https-everywhere-checker/

I notice that the license in gvgen.py is still gpl v2-not-later.  Was it not possible to relicense it?

Also it would be lovely if this repo could have a `LICENSE` file to better advertise its license, and also distros now usually require a separate license file for all packages, and rpm spec now has a `%license` field for this so it can be mandated.  Providing that license file makes it much easier for distros to redistribute it.

**Comment by stricaud** [comment]
ok let me learn how to release on pipy, I need to push this and other tools I have people ask for. 
Which license would work great for you? I am thinking MIT

**Comment by jayvdb** [comment]
Ya, MIT would be good.

**Comment by stricaud** [comment]
Alright, all done, you can now find it there:
https://pypi.org/project/GvGen/1.0/

**Comment by jayvdb** [comment]
Thanks
