### ISSUE TITLE
Inverse order in dot file

### ISSUE THREAD

**Issue by clemshubs** [stricaud/gvgen#5]
Hi !
First, thank you for this tool, it is very useful, I am using it to make a graph from a python AST.

I noticed that the order of nodes is inverted: 
If I add a node C1 then a node C2, the dot file generated will have the nodes inverted, and therefore messing with interpretation by Graphviz.

Example :
```
>>> c=g.newItem("C")
>>> c1=g.newItem("C1",c)
>>> c2=g.newItem("C2",c)
>>> g.dot()
/* Generated by GvGen v.0.9.1 (http://www.picviz.com/sections/opensource/gvgen.html) */

digraph G {
compound=true;
   node6 [label="C"];
   subgraph cluster7 {
   label="C";
      node9 [label="C2"];
      node8 [label="C1"];
   }
}
```

Do you have an idea of what is causing this ?

**Comment by stricaud** [comment]
Thanks for your feedback. This is a good catch, I will definitely have a look at this and find a way to fix it. I have no idea as it has been a while I have not touched the code.

**Comment by clemshubs** [comment]
Hi,

I may have found where the bug comes from :

line 104, before inserting in the node array, you test if it has a parent and insert it first on the list.
But the comment suggest that what you were willing to test was if it was a parent.

```
        # We now insert into gvgen datastructure
        self.__id += 1
        node = {'id': self.__id,        # Internal ID
                'lock': 0,              # When the node is written, it is locked to avoid further references
                'parent': parent,       # Node parent for easy graphviz clusters
                'style': None,          # Style that GvGen allow you to create
                'properties': {         # Custom graphviz properties you can add, which will overide previously defined styles
                       'label': name
                   }
                }

        # Parents should be sorted first
        if parent:
                self.__nodes.insert(1, node)
        else:
                self.__nodes.append(node)

        return node
```

Hope it makes sense... 

I understand the need to put parent first, I am triying to patch it, but I think this test is not appropriate :)
I deleted the test and it runs fine.
Let me know what you think!
