### ISSUE TITLE
Legend messes up my work !

### ISSUE THREAD

**Issue by clemshubs** [stricaud/gvgen#7]
Hi,

I am still using GvGen and i discoverd the Legend API.

That is a great idea, but it forces the whole graph in LR rankdir mode and it messes up my graph. #sad 

But as I am struggling to have different rank dirs in the same graph, I suppose you did too, hence this non optimal solution.
Any idea on how to fix it ?

[edit]
One idea, suboptimal too, would be to chack if rankdir is already "LR" or "RL".
If so, we can keep it like this.
If not (hence TB or BT), we can add a white link between the node that will force them in TB configuration.

Not ideal if background isn't white, and let a white pixel on the node border, but would do the trick...

Cheers,
Clement

**Comment by clemshubs** [comment]
Hi, 

It seems invisible links are a thing and it would fit the job nicely, giving we test _rankdir_ first.

I'll fix it and ask a pull request !

Cheers,
Clement

**Comment by stricaud** [comment]
thank you *very* much for this, merged and glad you made this contribution, feel free to continue the great work!
