### ISSUE TITLE
Subgraphs of subgraphs 

### ISSUE THREAD

**Issue by clemshubs** [stricaud/gvgen#9]
Hi,

I was trying to do subgraphs within subgraph and it fails. #sad

Here is my test :

```
from gvgen import *
g = GvGen()
main=g.newItem("main")
a=g.newItem("a",main)
main2=g.newItem("main2",main)
b = g.newItem("b",main2)
main3 = g.newItem("main3",main2)
c = g.newItem("c",main3)
g.dot()
```

At the end, there should be a box within a box within a box within a box but gvgen thinks otherwise :(

When plotted by webgraphviz, there are only two boxes.

I'll try to fix it.

Cheers,
CHA

**Comment by clemshubs** [comment]
Hi,

I think the evaluation of the ree in the '''tree()''' function isn't correct if the order of the node isn't either.
To be more specific : the output of '''tree()''' depends on the orders of the nodes.

But I think there are more problems than just an ordering of the things, some semicolons apearing for no reasons in the DOT output :-/

A fix could be to:
- Sort properly the tree (from top to bottom)
- Redo the "drawing" part to take into account this order 

The new drawing algorithm could be:
for each node, 
- set properties
- draw the node without children 
- call the function on the ones with children (i.e. subgraphs) until thay are no nodes lefts.

It may work, I'll try to implement it.

Cheers,
CHA

**Comment by stricaud** [comment]
this sounds fair, please if you have time to implement that would be great. I agree this should work as you expect and described earlier. You've hit a nice bug :) Tell me if you need help, but it seems you know what you are doing based on your previous PR!
